version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: furniture-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: furniture_inventory
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: appsecret
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/postgres:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: furniture-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - '5050:80'
    depends_on:
      - postgres

volumes:
  postgres_data:
